version: "3"
services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./project/:/var/www/html
    user: "1000:1000"
  php:
    build:
      context: ./.docker
      dockerfile: php/Dockerfile
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=localhost client_port=9003 discover_client_host=true
    networks:
      - internal
    volumes:
      - ./project/:/var/www/html
    user: "1000:1000"
  composer:
    image: composer
    user: "1000:1000"
    volumes:
      - ./:/app

networks:
  internal:
    driver: bridge