version: "3"
services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./project:/var/www/html
    user: ${UID}:${GID}
  php:
    build:
      context: ./.docker
      dockerfile: php/Dockerfile
      args:
        USER_ID: ${UID:-0}
        GROUP_ID: ${GID:-0}
        INSTALL_REDIS: "false"
        DB_DRIVER: "none"
    tty: true
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=localhost client_port=9003 discover_client_host=true start_on_request=yes
    networks:
      - internal
    volumes:
      - ./project/:/var/www/html
    user: ${UID}:${GID}
  composer:
    image: composer
    volumes:
      - ./project:/app
    user: ${UID}:${GID}
    depends_on:
      - php
    command: composer install

networks:
  internal:
    driver: bridge